apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "mobilint-device-plugin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mobilint-device-plugin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mobilint-device-plugin.selectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "mobilint-device-plugin.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "mobilint-device-plugin.fullname" . }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mobilint-device-plugin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: metrics
              containerPort: 9400
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
            periodSeconds: 5
            failureThreshold: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: cdi
              mountPath: /var/run/cdi
      volumes:
        - name: device-plugin
          hostPath:
            path: {{ .Values.kubeletDevicePluginsPath }}
            type: Directory
        - name: cdi
          hostPath:
            path: /var/run/cdi
            type: DirectoryOrCreate
