{{- if .Values.metrics.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mobilint-device-plugin.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mobilint-device-plugin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "mobilint-device-plugin.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 9400
      targetPort: metrics
      protocol: TCP
{{- end }}
{{- if .Values.metrics.serviceMonitor.enabled }}
{{- if not .Values.metrics.service.enabled -}}
{{- fail "metrics.serviceMonitor.enabled requires metrics.service.enabled=true" -}}
{{- end }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mobilint-device-plugin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mobilint-device-plugin.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mobilint-device-plugin.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
