apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mobilint-device-plugin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mobilint-device-plugin.labels" . | nindent 4 }}
